// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace molaryxadmin.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260810154604_initialMigration")]
    partial class initialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.IdentificationType", b =>
                {
                    b.Property<short>("IdIdentificationType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_identification_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdIdentificationType"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdIdentificationType");

                    b.ToTable("identification_types", (string)null);

                    b.HasData(
                        new
                        {
                            IdIdentificationType = (short)1,
                            Code = "CC",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cédula de ciudadanía"
                        },
                        new
                        {
                            IdIdentificationType = (short)2,
                            Code = "CE",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Cédula de extranjería"
                        },
                        new
                        {
                            IdIdentificationType = (short)3,
                            Code = "TI",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Tarjeta de identidad"
                        },
                        new
                        {
                            IdIdentificationType = (short)4,
                            Code = "NIT",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Número de Identificación Tributaria"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Property<short>("IdModule")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_module");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdModule"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdModule");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("modules", (string)null);

                    b.HasData(
                        new
                        {
                            IdModule = (short)1,
                            Code = "TENANTS",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            IdModule = (short)2,
                            Code = "USERS",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            IdModule = (short)3,
                            Code = "PATIENTS",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<long>("IdPasswordResetToken")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_password_reset_token");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdPasswordResetToken"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("used_at");

                    b.HasKey("IdPasswordResetToken");

                    b.HasIndex("IdUser");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Property<short>("IdPermission")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_permission");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdPermission"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<short>("IdModule")
                        .HasColumnType("smallint")
                        .HasColumnName("id_module");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdPermission");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IdModule");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            IdPermission = (short)1,
                            Code = "GET_TENANTS",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdModule = (short)1
                        },
                        new
                        {
                            IdPermission = (short)2,
                            Code = "ACTIVATE_TENANT",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdModule = (short)1
                        },
                        new
                        {
                            IdPermission = (short)3,
                            Code = "CREATE_BUSINESS_TENANT",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            IdModule = (short)1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Plan", b =>
                {
                    b.Property<short>("IdPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_plan");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdPlan"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<short?>("MaxAssistants")
                        .HasColumnType("smallint")
                        .HasColumnName("max_assistants");

                    b.Property<int?>("MaxPatients")
                        .HasColumnType("integer")
                        .HasColumnName("max_patients");

                    b.Property<short?>("MaxProfessionals")
                        .HasColumnType("smallint")
                        .HasColumnName("max_professionals");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdPlan");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("plans", (string)null);

                    b.HasData(
                        new
                        {
                            IdPlan = (short)1,
                            Code = "BASIC",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plan básico para consultorios pequeños.",
                            IsActive = true,
                            MaxAssistants = (short)1,
                            MaxPatients = 500,
                            MaxProfessionals = (short)1,
                            Name = "Basic",
                            Price = 79900m
                        },
                        new
                        {
                            IdPlan = (short)2,
                            Code = "PROFESSIONAL",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plan para consultorios en crecimiento.",
                            IsActive = true,
                            MaxAssistants = (short)3,
                            MaxPatients = 2000,
                            MaxProfessionals = (short)3,
                            Name = "Professional",
                            Price = 119900m
                        },
                        new
                        {
                            IdPlan = (short)3,
                            Code = "BUSINESS",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Plan para consultorios con equipos y operaciones de mayor escala.",
                            IsActive = true,
                            Name = "Business"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Promotion", b =>
                {
                    b.Property<long>("IdPromotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_promotion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdPromotion"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<short>("DurationMonths")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_months");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ends_at");

                    b.Property<short?>("IdTenantType")
                        .HasColumnType("smallint")
                        .HasColumnName("id_tenant_type");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdPromotion");

                    b.HasIndex("IdTenantType");

                    b.ToTable("promotions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PromotionPlan", b =>
                {
                    b.Property<long>("IdPromotion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_promotion");

                    b.Property<short>("IdPlan")
                        .HasColumnType("smallint")
                        .HasColumnName("id_plan");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.HasKey("IdPromotion", "IdPlan");

                    b.HasIndex("IdPlan");

                    b.ToTable("promotion_plans", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.Property<short>("IdUserRole")
                        .HasColumnType("smallint");

                    b.Property<short>("IdPermission")
                        .HasColumnType("smallint");

                    b.HasKey("IdUserRole", "IdPermission");

                    b.HasIndex("IdPermission");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            IdUserRole = (short)1,
                            IdPermission = (short)1
                        },
                        new
                        {
                            IdUserRole = (short)1,
                            IdPermission = (short)2
                        });
                });

            modelBuilder.Entity("Domain.Entities.Tenant", b =>
                {
                    b.Property<long>("IdTenant")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tenant");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdTenant"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("ConsultoryName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("consultory_name");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<short?>("IdIdentificationType")
                        .HasColumnType("smallint")
                        .HasColumnName("id_identification_type");

                    b.Property<short>("IdTenantStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("id_tenant_status");

                    b.Property<short>("IdTenantType")
                        .HasColumnType("smallint")
                        .HasColumnName("id_tenant_type");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("identification_number");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdTenant");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdIdentificationType");

                    b.HasIndex("IdTenantStatus");

                    b.HasIndex("IdTenantType");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TenantStatus", b =>
                {
                    b.Property<short>("IdTenantStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_tenant_status");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdTenantStatus"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdTenantStatus");

                    b.ToTable("tenant_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            IdTenantStatus = (short)1,
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Activo"
                        },
                        new
                        {
                            IdTenantStatus = (short)2,
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Inactivo"
                        },
                        new
                        {
                            IdTenantStatus = (short)3,
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pendiente"
                        },
                        new
                        {
                            IdTenantStatus = (short)4,
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bloqueado"
                        },
                        new
                        {
                            IdTenantStatus = (short)5,
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Rechazado"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TenantSubscription", b =>
                {
                    b.Property<long>("IdTenantSubscription")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_tenant_subscription");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdTenantSubscription"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndsAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("ends_at");

                    b.Property<short>("IdPlan")
                        .HasColumnType("smallint")
                        .HasColumnName("id_plan");

                    b.Property<long?>("IdPromotion")
                        .HasColumnType("bigint")
                        .HasColumnName("id_promotion");

                    b.Property<long>("IdTenant")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tenant");

                    b.Property<short>("IdTenantSubscriptionStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("id_tenant_subscription_status");

                    b.Property<short?>("MaxAssistants")
                        .HasColumnType("smallint")
                        .HasColumnName("max_assistants");

                    b.Property<int?>("MaxPatients")
                        .HasColumnType("integer")
                        .HasColumnName("max_patients");

                    b.Property<short?>("MaxProfessionals")
                        .HasColumnType("smallint")
                        .HasColumnName("max_professionals");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PromotionEndsAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("promotion_ends_at");

                    b.Property<DateTime?>("StartsAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdTenantSubscription");

                    b.HasIndex("IdPlan");

                    b.HasIndex("IdPromotion");

                    b.HasIndex("IdTenant")
                        .IsUnique()
                        .HasFilter("id_tenant_subscription_status = 2");

                    b.HasIndex("IdTenantSubscriptionStatus");

                    b.ToTable("tenant_subscriptions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TenantSubscriptionStatus", b =>
                {
                    b.Property<short>("IdTenantSubscriptionStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_tenant_subscription_status");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdTenantSubscriptionStatus"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdTenantSubscriptionStatus");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tenant_subscription_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            IdTenantSubscriptionStatus = (short)1,
                            Code = "PENDING",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "La suscripción está pendiente de activación.",
                            Name = "Pendiente"
                        },
                        new
                        {
                            IdTenantSubscriptionStatus = (short)2,
                            Code = "ACTIVE",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "La suscripción se encuentra activa.",
                            Name = "Activa"
                        },
                        new
                        {
                            IdTenantSubscriptionStatus = (short)3,
                            Code = "SCHEDULED",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "La suscripción ha sido programada para comenzar en una fecha futura.",
                            Name = "Programada"
                        },
                        new
                        {
                            IdTenantSubscriptionStatus = (short)4,
                            Code = "CANCELLED",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "La suscripción ha sido cancelada.",
                            Name = "Cancelada"
                        },
                        new
                        {
                            IdTenantSubscriptionStatus = (short)5,
                            Code = "EXPIRED",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "La suscripción ha expirado.",
                            Name = "Expirada"
                        },
                        new
                        {
                            IdTenantSubscriptionStatus = (short)6,
                            Code = "SUSPENDED",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "La suscripción ha sido suspendida temporalmente.",
                            Name = "Suspendido"
                        });
                });

            modelBuilder.Entity("Domain.Entities.TenantType", b =>
                {
                    b.Property<short>("IdTenantType")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_tenant_type");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdTenantType"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdTenantType");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("tenant_types", (string)null);

                    b.HasData(
                        new
                        {
                            IdTenantType = (short)1,
                            Code = "STANDARD",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            IdTenantType = (short)2,
                            Code = "FOUNDER",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<long>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUser"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("FirstSurname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_surname");

                    b.Property<short>("IdIdentificationType")
                        .HasColumnType("smallint")
                        .HasColumnName("id_identification_type");

                    b.Property<long?>("IdTenant")
                        .HasColumnType("bigint")
                        .HasColumnName("id_tenant");

                    b.Property<short>("IdUserRole")
                        .HasColumnType("smallint")
                        .HasColumnName("id_user_rol");

                    b.Property<short>("IdUserStatus")
                        .HasColumnType("smallint")
                        .HasColumnName("id_user_status");

                    b.Property<string>("IdentificationNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("identification_number");

                    b.Property<byte[]>("Password")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<byte[]>("Salt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("salt");

                    b.Property<string>("SecondName")
                        .HasColumnType("text")
                        .HasColumnName("second_name");

                    b.Property<string>("SecondSurname")
                        .HasColumnType("text")
                        .HasColumnName("second_surname");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("IdUser");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdIdentificationType");

                    b.HasIndex("IdTenant");

                    b.HasIndex("IdUserRole");

                    b.HasIndex("IdUserStatus");

                    b.HasIndex("IdentificationNumber")
                        .IsUnique();

                    b.HasIndex("PhoneNumber")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Property<short>("IdUserRole")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_user_role");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdUserRole"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdUserRole");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            IdUserRole = (short)1,
                            Code = "SUPER_ADMIN",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acceso completo a la plataforma y administración global de todos los consultorios.",
                            Name = "Super Administrador"
                        },
                        new
                        {
                            IdUserRole = (short)2,
                            Code = "OWNER",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acceso completo a la gestión de su consultorio y sus operaciones.",
                            Name = "Propietario"
                        },
                        new
                        {
                            IdUserRole = (short)4,
                            Code = "PROFESSIONAL",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acceso a las funcionalidades clínicas y gestión de la atención de pacientes.",
                            Name = "Profesional"
                        },
                        new
                        {
                            IdUserRole = (short)5,
                            Code = "ASSISTANT",
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acceso a las funcionalidades administrativas y operativas asignadas.",
                            Name = "Asistente"
                        });
                });

            modelBuilder.Entity("Domain.Entities.UserSession", b =>
                {
                    b.Property<long>("IdUserSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_user_session");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdUserSession"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Device")
                        .HasColumnType("text")
                        .HasColumnName("device");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("expires_at");

                    b.Property<long>("IdUser")
                        .HasColumnType("bigint")
                        .HasColumnName("id_user");

                    b.Property<string>("IpConnection")
                        .HasColumnType("text")
                        .HasColumnName("ip_connection");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token_hash");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("revoked_at");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdUserSession");

                    b.HasIndex("IdUser");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique();

                    b.ToTable("user_sessions", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserStatus", b =>
                {
                    b.Property<short>("IdUserStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("id_user_status");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("IdUserStatus"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("IdUserStatus");

                    b.ToTable("user_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            IdUserStatus = (short)1,
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Activo"
                        },
                        new
                        {
                            IdUserStatus = (short)2,
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Inactivo"
                        },
                        new
                        {
                            IdUserStatus = (short)3,
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Pendiente"
                        },
                        new
                        {
                            IdUserStatus = (short)4,
                            CreatedAt = new DateTime(2026, 7, 22, 0, 0, 0, 0, DateTimeKind.Utc),
                            Name = "Bloqueado"
                        });
                });

            modelBuilder.Entity("Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("PasswordResetTokens")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.HasOne("Domain.Entities.Module", "Module")
                        .WithMany("Permissions")
                        .HasForeignKey("IdModule")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("Domain.Entities.Promotion", b =>
                {
                    b.HasOne("Domain.Entities.TenantType", "TenantType")
                        .WithMany("Promotions")
                        .HasForeignKey("IdTenantType")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("TenantType");
                });

            modelBuilder.Entity("Domain.Entities.PromotionPlan", b =>
                {
                    b.HasOne("Domain.Entities.Plan", "Plan")
                        .WithMany("PromotionPlans")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Promotion", "Promotion")
                        .WithMany("PromotionPlans")
                        .HasForeignKey("IdPromotion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("IdPermission")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.UserRole", "UserRole")
                        .WithMany("RolePermissions")
                        .HasForeignKey("IdUserRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("UserRole");
                });

            modelBuilder.Entity("Domain.Entities.Tenant", b =>
                {
                    b.HasOne("Domain.Entities.IdentificationType", "IdentificationType")
                        .WithMany("Tenants")
                        .HasForeignKey("IdIdentificationType")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.TenantStatus", "TenantStatus")
                        .WithMany("Tenants")
                        .HasForeignKey("IdTenantStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TenantType", "TenantType")
                        .WithMany("Tenants")
                        .HasForeignKey("IdTenantType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdentificationType");

                    b.Navigation("TenantStatus");

                    b.Navigation("TenantType");
                });

            modelBuilder.Entity("Domain.Entities.TenantSubscription", b =>
                {
                    b.HasOne("Domain.Entities.Plan", "Plan")
                        .WithMany("TenantSubscriptions")
                        .HasForeignKey("IdPlan")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Promotion", "Promotion")
                        .WithMany("TenantSubscriptions")
                        .HasForeignKey("IdPromotion")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany("TenantSubscriptions")
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.TenantSubscriptionStatus", "TenantSubscriptionStatus")
                        .WithMany("TenantSubscriptions")
                        .HasForeignKey("IdTenantSubscriptionStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("Promotion");

                    b.Navigation("Tenant");

                    b.Navigation("TenantSubscriptionStatus");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.IdentificationType", "IdentificationType")
                        .WithMany("Users")
                        .HasForeignKey("IdIdentificationType")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("IdTenant")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.UserRole", "UserRole")
                        .WithMany("Users")
                        .HasForeignKey("IdUserRole")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.UserStatus", "UserStatus")
                        .WithMany("Users")
                        .HasForeignKey("IdUserStatus")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IdentificationType");

                    b.Navigation("Tenant");

                    b.Navigation("UserRole");

                    b.Navigation("UserStatus");
                });

            modelBuilder.Entity("Domain.Entities.UserSession", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserSessions")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.IdentificationType", b =>
                {
                    b.Navigation("Tenants");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Module", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Domain.Entities.Plan", b =>
                {
                    b.Navigation("PromotionPlans");

                    b.Navigation("TenantSubscriptions");
                });

            modelBuilder.Entity("Domain.Entities.Promotion", b =>
                {
                    b.Navigation("PromotionPlans");

                    b.Navigation("TenantSubscriptions");
                });

            modelBuilder.Entity("Domain.Entities.Tenant", b =>
                {
                    b.Navigation("TenantSubscriptions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.TenantStatus", b =>
                {
                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Domain.Entities.TenantSubscriptionStatus", b =>
                {
                    b.Navigation("TenantSubscriptions");
                });

            modelBuilder.Entity("Domain.Entities.TenantType", b =>
                {
                    b.Navigation("Promotions");

                    b.Navigation("Tenants");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("PasswordResetTokens");

                    b.Navigation("UserSessions");
                });

            modelBuilder.Entity("Domain.Entities.UserRole", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.UserStatus", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
